// {keycode : animation name}
export const animKeys = {
  KeyA: 'Armada',
  KeyB: 'Bencao',
  KeyC: 'Chapa',
  KeyD: 'Chapaeu De Couro',
  KeyE: 'Au',
  KeyG: 'Chapa Giratoria',
  KeyH: 'Chapa Giratoria Back',
  KeyI: 'Meia Lua De Frente',
  KeyJ: 'Meia Lua De Compasso',
  KeyK: 'Meia Lua De Compasso Back',
  KeyL: 'Martelo Do Chau Double',
  KeyM: 'Martelo Do Chau',
  KeyN: 'Martelo Do Chau Sem Mao',
  KeyP: 'Ponteira',
  KeyQ: 'Au To Role',
  KeyR: 'Rasteira',
  KeyS: 'Queshada',
  KeyT: 'Troca',
  KeyW: 'Martelo',
  KeyY: 'Macaco',
  KeyZ: 'Macaco Lateral',

  ArrowUp: 'Passo A Frente',
  ArrowDown: 'Cocorinha',
  ArrowLeft: 'Esquiva Baixa',
  ArrowRight: 'Esquiva Lateral',
  Enter: 'Armada To Esquiva',
  Space: 'Backflip',
}
